name: graphql_parser3
version: 3.0.0
description: Parses GraphQL queries and schemas. Also includes classes for the GraphQL AST.
homepage: https://github.com/raphrmx/graphql_parser3
repository: https://github.com/raphrmx/graphql_parser3
environment:
  sdk: '>=3.8.0 <4.0.0'
dependencies:
  charcode: ^1.4.0
  source_span: ^1.10.1
  string_scanner: ^1.4.1
dev_dependencies:
  matcher: ^0.12.17
  lints: ^6.0.0
  test: ^1.26.3
